### ISSUE TITLE
vim does not open

### ISSUE THREAD

**Issue by nkh** [mikezackles/vranger#6]
Hi, I cloned and put vranger and vrim in my Path,

when I run vranger, ranger opens but choosing a file to open fails.

did I miss something?

2 ~ vranger
/home/nadim/nadim/bin/vrim: 6: [: --: unexpected operator
/home/nadim/nadim/bin/vrim: 6: [: --: unexpected operator
/home/nadim/nadim/bin/vrim: 6: [: --: unexpected operator

**Comment by mikezackles** [comment]
Thanks for the bug report!

It seems like the vrim script isn't getting interpreted properly (which is probably my fault for using `#!/bin/sh` instead of bash). I'm going to take a wild guess that `/bin/sh` points to something other than bash? If not, what version of bash are you using?

In any case, I've pushed a commit that fixes the shebangs, which might fix your issue. Let me know!

**Comment by nkh** [comment]
It run and opens fine after your patch.

I either misunderstood vranger or I am using it wrong, maybe you can shed some light.

I see two use cases

1/ vim is running, a file needs to be chosen, ranger is used for that

2/ ranger is running, a file is chosen to be opened in vim. now case 1 can be embedded under this case

I try case 2:

vranger
chose a file -> edit in vim
\q
chose another file

what happens is that the first file gets closed if it was not modified, and if it was, one is prompted to save it and then returned in ranger, not in vi with the new file to edit

I'd like to be able to edit both file, preferably in tabs 

 
Also I'd rather configure the system, create aliases than having to remember more command. aliasing vim is fine as long as it work as usual, specially in vipe. how does one one make that happen.

**Comment by mikezackles** [comment]
A simple vranger session would look like this:
- run `vranger`
- edit file A
- press `<Leader>q`
- edit file B

At this point, file A and file B should both be open in vim buffers and are accessible using the normal vim buffer commands. Notice that you need to use `<Leader>q` to leave vim and not something like `:q`. This is because we don't actually want to stop vim; we just want to detach the tmux session in which it is running.

Does the scenario above not work for you? If not, are you using a version of vim that is compiled with +clientserver? (Use `vim --version` to see.) Are you running X11?

> I'd like to be able to edit both file, preferably in tabs

Up until now, vranger only supported buffers because that's what I use, but I just added tab support for you. To use it, start vranger like this:

```
VRANGER_USE_TABS=1 vranger
```

This can of course be aliased.

> Also I'd rather configure the system, create aliases than having to remember more command. aliasing vim is fine as long as it work as usual, specially in vipe. how does one one make that happen.

If I'm understanding you correctly, this isn't really how vranger works. The vrim script is not meant to be run outside the context of vranger (and should tell you so if you try). vranger pairs a single instance of ranger with a single instance of vim (running inside tmux). The only time you should need to think about the vrim script is if you're editing a file that ranger doesn't immediately identify as a text file.

If you want to launch ranger from _within_ vim, [try this](https://github.com/ranger/ranger/blob/master/examples/vim_file_chooser.vim).

**Comment by mikezackles** [comment]
I'm closing this since the original issue is resolved, but please feel free to continue the thread.

**Comment by nkh** [comment]
Hi,

Thank you for adding VRANGER_USE_TABS, its usability has decupled.
The ranger laucher was also a good addition, I modified it to open tabs too.

I didn't know about vim client-server before I discovered vranger, nice to know.

Before I forget, when in ranger, open a file in vi, get back to ranger, is there a way to get back into vi?
Changing session is possible, and easy enough, but if I close vi in that session, my terminal closes too, when I'd rather jump back to ranger.

You stated that opening a file (vranger -ranger-vi-\q) and then another file would have both in buffer in vim. I get a single buffer. if the buffer is modified, vim asks me to save it, I can then open a second file. using USE_TABS does fix the problem though.

I checked and only one file is open at the time in vim. Let me know if I can help further with that.

''''
s:$7:vrim_1478606978
    w:@18:[vim]
        p:0, 124 x 37 
            30118,vim -c nnoremap <silent> <Leader>q :call system("tmux detach -s vrim_1478606978")<CR> /home/nadim/nadim/devel/repositories/vranger/vranger
                /usr/bin/vim.basic
                /home/nadim/nadim/devel/repositories/vranger/.vrim.swp 
''''

Below is the output of vim -- version. When you believe this discussion, with the technical points, is over, I will explain further what I meant with configuring the system to have a simple flow with vim/vranger.

''''
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
-clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             -perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            -ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl-lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil-lm

''''

**Comment by mikezackles** [comment]
Sorry for the delay. It has been a busy week at work.

> Before I forget, when in ranger, open a file in vi, get back to ranger, is there a way to get back into vi?

~~There is no mechanism for this provided by vranger at the moment (and I'm not sure I see  an easy way to do it).~~ `:shell vrim` will do the trick. You could of course set up a shortcut for this.

In the name of full disclosure, I should mention that I've mostly phased this tool out of my workflow due to a switch to spacemacs. But I am starting to evolve a similar setup for emacs (which has better client server support).

> Below is the output of vim -- version. When you believe this discussion, with the technical points, is over, I will explain further what I meant with configuring the system to have a simple flow with vim/vranger.

Your vim is not compiled with clientserver enabled. (The part that says `-clientserver` should say `+clientserver`.) You could compile manually, or you might be able to install your distro's gvim package if there is one. You do not need to run the gui version, but it is my understanding that vim's client/server support is heavily coupled with the gui version, especially since it requires X11 for communication!

I would love to hear your thoughts on a simple flow.

**Comment by nkh** [comment]
Hi,

# :shell vrim

it opens another vrim, so there are two  instances of ranger running which makes it awkward when quitting as one is in multiple ranger sessions. I just want back in the vim session

```
s:$5:5
    w:@14:[ranger], 2 panes
        p:0, 138 x 20 
            28883,bash /home/nadim/nadim/bin/vranger
                /home/nadim/nadim/bin/vranger
                28891,/usr/bin/python -O /usr/bin/ranger
                    /usr/bin/python2.7
                    10410,/bin/sh -c set -- '/home/nadim/nadim/config/mediainfo.template'; $EDITOR -- "$@"
                        /bin/dash
                        10411,tmux -2 attach -t vrim_1479198487
                            /usr/local/bin/tmux
```

# gvim/vim sessions

I haven't had time to install and test with gvim, or recompile vim, it's in the todo list

# Work flow

Say we have command X

X allows us to
- move around in directories, when run with no argument or argument is directory
- edit files, when argument is a file
- if mixed arguments are provided, we are offered the possibility to select files first, then the editor is opened.
- an option to be left in ranger when all the files are edited
- while in X editing files, it is possible to chose other files vi X directory browsing
- there's only ever one "instance" of X running (problem I descrime in 1/ above)
- there is only one command/shortcut to go from X-browsing to X-editing
- opening files
  - give file names (plural) to open in the editor in a command line, in browsing mode  
  - open files in editor but stay in the browser
  - feedback, what files are currently open in the editor
- play nicely with Tmux; eg detach editor tab to another pane, and more importantly attach any editor pane to an X "session". Let's keep this one out for a moment, it complicates a bit.

X is is a mix of ranger, vranger, vim, ranger-vim plugin.

Problems (I have but I may have the wrong config):
- I start the wrong command.; I am used to start vim when in fact i want to be in vim through ranger, but I can't give a file name to vranger (which would have solved a  few problems)
- multiple shortcut to do the same thing
- indented sessions

**Comment by nkh** [comment]
if vranger would take the name of a vim session as argument, X could be written as a wrapper, it would open whatever files and jump in vranger
